[tool.poetry]
name = "athercore"
version = "0.1.0"
description = "Athercore trading system"
authors = ["Camer <you@example.com>"]
package-mode = false

[tool.poetry.dependencies]
python = ">=3.11,<3.12"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
addopts = "-q"
pythonpath = ["."]
testpaths = ["tests"]

[tool.ruff]
line-length = 100

[tool.ruff.lint]
select = ["E","F","I","UP","PLC","PLE"]

[dependency-groups]
dev = [
    "pandas-stubs (>=2.3.2.250926,<3.0.0.0)",
    "pre-commit (>=4.3.0,<5.0.0)"
]

[tool.mypy]
python_version = "3.11"
strict = true
ignore_missing_imports = true
disallow_untyped_defs = false
disallow_untyped_decorators = false
disable_error_code = ["misc"]
