name: CI

on:
  push:
  pull_request:

jobs:
  test-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install runtime deps (requirements.txt)
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Install dev tools (pre-commit, pytest, mypy, ruff, detect-secrets)
        run: |
          pip install pre-commit pytest mypy ruff detect-secrets

      - name: Prepare detect-secrets baseline if missing
        run: |
          if [ ! -f .secrets.baseline ]; then
            detect-secrets scan --all-files . > .secrets.baseline
          fi

      - name: Run pre-commit on all files (black, ruff, mypy, detect-secrets)
        run: |
          pre-commit install
          pre-commit run --all-files

      - name: Run tests with coverage
  run: |
    pytest --cov=apps --cov=core --cov-report=xml
- name: Upload coverage to Codecov
  uses: codecov/codecov-action@v5
  with:
    files: ./coverage.xml
    fail_ci_if_error: true
