      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: infra/docker/Dockerfile
          push: true
          tags: ghcr.io/drprofessorphd/athercore:latest
